// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvBm0PiChYCErjpvCykGn9YMdHtiHsqWc',
    appId: '1:1043730837669:web:259abdca3d19895db99d4c',
    messagingSenderId: '1043730837669',
    projectId: 'floodaid-flutter',
    authDomain: 'floodaid-flutter.firebaseapp.com',
    databaseURL: 'https://floodaid-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'floodaid-flutter.firebasestorage.app',
    measurementId: 'G-4DWVM1PM00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4ah-JpI-afi1fJnXRp54YdmVa5_JglQ',
    appId: '1:1043730837669:android:dd9e05fae86ae7cab99d4c',
    messagingSenderId: '1043730837669',
    projectId: 'floodaid-flutter',
    databaseURL: 'https://floodaid-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'floodaid-flutter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcpV7JOuCgNvXgwyyM46yHK0-NkKI67A0',
    appId: '1:1043730837669:ios:6393753ba15dd119b99d4c',
    messagingSenderId: '1043730837669',
    projectId: 'floodaid-flutter',
    databaseURL: 'https://floodaid-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'floodaid-flutter.firebasestorage.app',
    iosBundleId: 'com.example.floodaidFlutter',
  );
}
